baseURL = "/"
languageCode = "en-us"
title = "Woahuh's site"
theme = "PaperMod"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/home"
    weight = 1

  [[menu.main]]
    name = "Blogs"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 3
